### ISSUE TITLE
Any plans to update this to the latest snowflake_grant_privileges_to_role resource? 

### ISSUE THREAD

**Issue by justincandoit** [getindata/terraform-snowflake-role#8]
https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_role

**Comment by jakubigla** [comment]
Hi @justincandoit, thanks for getting in touch.
Yes, we are currently doing some refactoring to take advantage of this new resource and we're targeting to complete this by the end of January

**Comment by moss2k13** [comment]
@justincandoit it is done starting from version [v2.0.0](https://github.com/getindata/terraform-snowflake-role/releases/tag/v2.0.0)
